[package]
name = "tokio-udt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
tokio = { version = "1.*", features = [ "macros", "net", "io-util", "sync", "time", "rt-multi-thread" ] }
sha2 = "*"
once_cell = "*"
socket2 = "*"
nix = "*"

clap = { version = "3.1.15", features = ["derive"] }
